Document: j1708-drivers
Title: Debian j1708-drivers Manual
Author: <insert document author here>
Abstract: This manual describes what j1708-drivers is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/j1708-drivers/j1708-drivers.sgml.gz

Format: postscript
Files: /usr/share/doc/j1708-drivers/j1708-drivers.ps.gz

Format: text
Files: /usr/share/doc/j1708-drivers/j1708-drivers.text.gz

Format: HTML
Index: /usr/share/doc/j1708-drivers/html/index.html
Files: /usr/share/doc/j1708-drivers/html/*.html
